### ISSUE TITLE
HEALTHCHECK not workinng

### ISSUE THREAD

**Issue by darrenfang** [juris/docker-zkui#1]
/bin/sh: curl: not found

**Comment by xiaoyao9184** [comment]
same, change it to use `netcat` check port up or disable it

```yaml
services:
  zkui:
    healthcheck:
      test: nc -z -v -w5 localhost 9090
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
```

```yaml
services:
  zkui:
    healthcheck:
      disable: true
```
